### ISSUE TITLE
Extra copies, no match submatch []byte should be nil, negative indexes causing panics?

### ISSUE THREAD

**Issue by tv42** [icholy/replace#2]
I haven't tested any of these but based on a quick read of the source, I'm left with a few thoughts/doubts. I'm putting them into a single issue because they sort of form a progression of thoughts, and they're kinda tiny (and I'm lazy -- sorry!)

It wasn't immediately obvious why RegexpStringSubmatchFunc copies the submatches, instead of just slicing src.

RegexpStringSubmatchFunc copying bytes to tmp before stringifying tmp is even more mysterious.

I think the code might have lost the nil aspect of this regexp behavior: "If an index is negative or text is nil, it means that subexpression did not match any string in the input."

It might also just panic because it's doing slicing with a potentially negative index?

**Comment by icholy** [comment]
Thanks for looking this over, I really appreciate the feedback.

* Removed the extra copy in `RegexpStringSubmatchFunc`, and `RegexpStringFunc `.
* Fixed the negative index panic.

I went back and forth on copying the matches for the `[]byte` variations. My thinking was that, if someone really wanted to avoid the extra copy, they could do it with `RegexpIndexFunc`. And anyone who would go to that effort would actually read the doc.

**Comment by icholy** [comment]
I ended up completely removing the copying.
